import {
  UserProfile,
  Task,
  DSATopic,
  DSAPattern,
  Problem,
  RoadmapDayItem,
  WebDevTopic,
  ProjectItem,
  HabitItem,
  MoodEntry,
  JobApplicationItem,
  JobListing,
  StudySessionItem,
} from '@/types';

export const initialUserProfile: UserProfile = {
  id: 'usr_default_101',
  name: 'Nikhitha',
  email: 'nikhitha.dev@example.com',
  targetRole: 'SDE-1',
  targetCompanies: ['Amazon', 'Microsoft', 'Google', 'Uber', 'Atlassian'],
  skills: ['JavaScript', 'TypeScript', 'React', 'Node.js', 'C++', 'Python', 'SQL'],
  experienceYears: 0.5,
  graduationYear: 2025,
  preferredLocations: ['Bangalore', 'Hyderabad', 'Remote'],
  dailyStudyTarget: 5.0,
  goalTitle: 'Become Amazon SDE-1 interview ready',
  currentStreak: 0,
  longestStreak: 0,
};

export const initialRoadmapDays: RoadmapDayItem[] = [
  {
    id: 'day-1',
    dayNumber: 1,
    phaseTitle: 'Phase 1: Foundation & Complexity',
    theme: 'Language Basics & Asymptotic Analysis',
    dsaFocus: 'Big-O notation, Time & Space Complexity, Memory layout',
    webDevFocus: 'HTML5 Semantic tags, Modern CSS Box Model',
    csFocus: 'Process vs Thread, Memory Hierarchy',
    targetHours: 4.5,
    isCompleted: false,
  },
  {
    id: 'day-7',
    dayNumber: 7,
    phaseTitle: 'Phase 1: Foundation & Arrays',
    theme: 'Two Pointers & Frequency Arrays',
    dsaFocus: 'Two Sum II, Container With Most Water, 3Sum',
    webDevFocus: 'JavaScript ES6+, Scope, Closures',
    csFocus: 'TCP 3-way handshake, HTTP vs HTTPS',
    targetHours: 5.0,
    isCompleted: false,
  },
  {
    id: 'day-14',
    dayNumber: 14,
    phaseTitle: 'Phase 2: Core Data Structures',
    theme: 'Sliding Window & Hashing',
    dsaFocus: 'Longest Substring Without Repeating Characters, Minimum Window Substring',
    webDevFocus: 'DOM Manipulation, Event Bubbling, Promises',
    csFocus: 'Virtual Memory, Paging, Page Faults',
    targetHours: 5.0,
    isCompleted: false,
  },
  {
    id: 'day-23',
    dayNumber: 23,
    phaseTitle: 'Phase 2: Core Data Structures',
    theme: 'Binary Search & React Hooks',
    dsaFocus: 'Search in Rotated Sorted Array, Find Minimum in Rotated Sorted Array, Search on Answer',
    webDevFocus: 'React useEffect lifecycle, Custom Hooks, Dependency Array pitfall',
    projectsFocus: 'Employee Offboarding: JWT Authentication middleware & Refresh tokens',
    revisionFocus: 'Revise Sliding Window problems & HashMap + Prefix Sum pattern',
    targetHours: 5.5,
    isCompleted: false,
    notes: "Derived binary search invariant carefully before coding.",
  },
  {
    id: 'day-24',
    dayNumber: 24,
    phaseTitle: 'Phase 2: Core Data Structures',
    theme: 'Linked Lists & React State Management',
    dsaFocus: 'Reverse Linked List, Cycle Detection (Floyd), Merge K Sorted Lists',
    webDevFocus: 'React Context API vs Zustand / Redux Toolkit',
    targetHours: 5.0,
    isCompleted: false,
  },
  {
    id: 'day-35',
    dayNumber: 35,
    phaseTitle: 'Phase 3: Intermediate Trees & Graphs',
    theme: 'Binary Trees & BFS/DFS Traversal',
    dsaFocus: 'Lowest Common Ancestor, Tree Diameter, Level Order Traversal',
    webDevFocus: 'Node.js Event Loop, Stream API, Express REST APIs',
    csFocus: 'DBMS Indexing, B-Trees vs Hash Indexes, Normalization',
    targetHours: 5.5,
    isCompleted: false,
  },
  {
    id: 'day-50',
    dayNumber: 50,
    phaseTitle: 'Phase 4: Dynamic Programming & System Design',
    theme: '1D DP & Low Level Design',
    dsaFocus: 'House Robber, Coin Change, Longest Increasing Subsequence',
    lldFocus: 'Design Parking Lot, Factory Pattern, Strategy Pattern',
    webDevFocus: 'MongoDB Aggregations, Mongoose Indexing',
    targetHours: 6.0,
    isCompleted: false,
  },
  {
    id: 'day-75',
    dayNumber: 75,
    phaseTitle: 'Phase 5: High Level Design & Interview Sprints',
    theme: 'HLD Architecture & Graph Hard Problems',
    dsaFocus: 'Dijkstra, Word Ladder II, Alien Dictionary',
    hldFocus: 'Design URL Shortener, Rate Limiter, Load Balancing & CDN',
    appsFocus: 'Apply to 10 Tier-1 Product Companies, LinkedIn InMails',
    targetHours: 6.0,
    isCompleted: false,
  },
  {
    id: 'day-100',
    dayNumber: 100,
    phaseTitle: 'Phase 6: Final FAANG Mock Sprints',
    theme: 'Full Simulation & Bar Raiser Prep',
    dsaFocus: 'Timed 45-min LeetCode Hard mock rounds with voice recording',
    appsFocus: 'Onsite interview rounds & Offer negotiation',
    targetHours: 6.0,
    isCompleted: false,
  },
];

export const initialDSATopics: DSATopic[] = [
  {
    id: 'top-1',
    name: 'Programming Fundamentals',
    slug: 'programming-fundamentals',
    category: 'DSA',
    progressionLevel: 'BEGINNER',
    description: 'Variables, loops, conditionals, functions, memory references, and recursion basics',
    theory: 'Execution stack, primitive vs non-primitive memory allocation, recursion termination conditions.',
    templates: 'void recursiveSolve(int index, vector<int>& state) { if (baseCondition) return; ... }',
    patternsCount: 3,
    problemsCount: 15,
    solvedCount: 0,
    confidence: 0,
  },
  {
    id: 'top-2',
    name: 'Complexity Analysis',
    slug: 'complexity-analysis',
    category: 'DSA',
    progressionLevel: 'BEGINNER',
    description: 'O(1), O(log n), O(n), O(n log n), O(n²), O(2^n), O(n!) asymptotic notation',
    theory: 'Master Theorem, recurrence relations, auxiliary space vs stack space.',
    patternsCount: 2,
    problemsCount: 10,
    solvedCount: 0,
    confidence: 0,
  },
  {
    id: 'top-3',
    name: 'Arrays & Strings',
    slug: 'arrays-and-strings',
    category: 'DSA',
    progressionLevel: 'BEGINNER',
    description: 'Contiguous memory, Kadane algorithm, frequency counts, in-place manipulation',
    theory: 'Contiguous cache locality, amortization, string immutability in JS/Python/Java.',
    templates: 'int maxSubarraySum(vector<int>& nums) { int cur = 0, best = nums[0]; ... }',
    patternsCount: 5,
    problemsCount: 28,
    solvedCount: 0,
    confidence: 0,
  },
  {
    id: 'top-4',
    name: 'Hashing & HashMaps',
    slug: 'hashing',
    category: 'DSA',
    progressionLevel: 'BEGINNER',
    description: 'Direct addressing, collision handling, frequency maps, set lookups',
    theory: 'Separate chaining, open addressing, amortized O(1) lookup vs O(n) worst case on hash collisions.',
    patternsCount: 4,
    problemsCount: 22,
    solvedCount: 0,
    confidence: 0,
  },
  {
    id: 'top-5',
    name: 'Two Pointers',
    slug: 'two-pointers',
    category: 'DSA',
    progressionLevel: 'BEGINNER',
    description: 'Opposite direction, same direction (fast & slow), sorted array pruning',
    theory: 'Reducing O(n²) pair comparisons to O(n) by exploiting monotonicity in sorted arrays.',
    templates: 'while (left < right) { int sum = arr[left] + arr[right]; if (sum == target) ... else if (sum < target) left++; else right--; }',
    patternsCount: 4,
    problemsCount: 20,
    solvedCount: 0,
    confidence: 0,
  },
  {
    id: 'top-6',
    name: 'Sliding Window',
    slug: 'sliding-window',
    category: 'DSA',
    progressionLevel: 'BEGINNER',
    description: 'Fixed-size window, dynamic-size window, condition expansion and contraction',
    theory: 'Maintains subarray invariant using right pointer for expansion and left pointer for contraction. Ensures linear O(n) traversal.',
    templates: 'for (int r = 0; r < n; r++) { add(arr[r]); while (!valid()) { remove(arr[l++]); } updateAns(); }',
    patternsCount: 3,
    problemsCount: 18,
    solvedCount: 0,
    confidence: 0,
  },
  {
    id: 'top-7',
    name: 'Prefix Sum',
    slug: 'prefix-sum',
    category: 'DSA',
    progressionLevel: 'BEGINNER',
    description: 'Range sum queries in O(1), subarray sum equals k with hashmap',
    theory: 'Prefix[i] = Prefix[i-1] + arr[i]. Subarray sum from L to R is Prefix[R] - Prefix[L-1].',
    patternsCount: 2,
    problemsCount: 14,
    solvedCount: 0,
    confidence: 0,
  },
  {
    id: 'top-8',
    name: 'Binary Search',
    slug: 'binary-search',
    category: 'DSA',
    progressionLevel: 'INTERMEDIATE',
    description: 'Standard search, search in rotated sorted array, search on answer space (monotonic predicate)',
    theory: 'Halving the search space per iteration using monotonicity. Essential condition: f(mid) is monotonic boolean predicate.',
    templates: 'int low = 0, high = n - 1; while (low <= high) { int mid = low + (high - low)/2; if (condition(mid)) ans = mid, high = mid - 1; else low = mid + 1; }',
    patternsCount: 4,
    problemsCount: 24,
    solvedCount: 0,
    confidence: 0,
  },
  {
    id: 'top-9',
    name: 'Linked Lists',
    slug: 'linked-lists',
    category: 'DSA',
    progressionLevel: 'BEGINNER',
    description: 'Singly, doubly, cycle detection (Floyd’s algorithm), reversal, fast & slow pointers',
    theory: 'Pointer manipulation, dummy head node pattern to simplify edge cases.',
    patternsCount: 4,
    problemsCount: 18,
    solvedCount: 0,
    confidence: 0,
  },
  {
    id: 'top-10',
    name: 'Stack & Queue',
    slug: 'stack-and-queue',
    category: 'DSA',
    progressionLevel: 'BEGINNER',
    description: 'LIFO, FIFO, Monotonic Stack (next greater element), Sliding Window Maximum (deque)',
    theory: 'Monotonic stack preserves sorted order of indices to resolve nearest greater/smaller queries in O(n) total time.',
    templates: 'stack<int> st; for (int i=0; i<n; i++) { while(!st.empty() && arr[st.top()] < arr[i]) { nextGreater[st.top()] = arr[i]; st.pop(); } st.push(i); }',
    patternsCount: 3,
    problemsCount: 16,
    solvedCount: 0,
    confidence: 0,
  },
  {
    id: 'top-11',
    name: 'Trees & BST',
    slug: 'trees-and-bst',
    category: 'DSA',
    progressionLevel: 'INTERMEDIATE',
    description: 'Preorder/Inorder/Postorder/Levelorder, Lowest Common Ancestor, BST validation & search',
    theory: 'Recursive tree traversal patterns: bottom-up information aggregation vs top-down path validation.',
    patternsCount: 5,
    problemsCount: 30,
    solvedCount: 0,
    confidence: 0,
  },
  {
    id: 'top-12',
    name: 'Heap / Priority Queue',
    slug: 'heap',
    category: 'DSA',
    progressionLevel: 'INTERMEDIATE',
    description: 'Min-Heap, Max-Heap, Top K elements, K-way merge, two heaps for running median',
    theory: 'Complete binary tree, array representation where parent = (i-1)/2, children = 2i+1, 2i+2. O(log k) insertion/extraction.',
    patternsCount: 3,
    problemsCount: 15,
    solvedCount: 0,
    confidence: 0,
  },
  {
    id: 'top-13',
    name: 'Graphs',
    slug: 'graphs',
    category: 'DSA',
    progressionLevel: 'ADVANCED',
    description: 'Adjacency list/matrix, BFS, DFS, Cycle detection, Bipartite check',
    theory: 'Visited arrays, recursion stack tracking for directed cycles, queue for shortest path in unweighted graphs.',
    patternsCount: 5,
    problemsCount: 26,
    solvedCount: 0,
    confidence: 0,
  },
  {
    id: 'top-14',
    name: 'Dynamic Programming',
    slug: 'dynamic-programming',
    category: 'DSA',
    progressionLevel: 'ADVANCED',
    description: '1D DP, 2D Grid DP, 0/1 Knapsack, Unbounded Knapsack, Longest Common Subsequence, DP on Trees',
    theory: 'Overlapping subproblems and optimal substructure. State definition, base cases, transition relation, space optimization.',
    templates: 'int dp[n+1]; dp[0] = base; for(int i=1; i<=n; i++) dp[i] = min/max(dp[i-k] + cost);',
    patternsCount: 6,
    problemsCount: 35,
    solvedCount: 0,
    confidence: 0,
  },
  {
    id: 'top-15',
    name: 'Trie & Union Find',
    slug: 'trie-and-union-find',
    category: 'DSA',
    progressionLevel: 'ADVANCED',
    description: 'Prefix tree for strings/XOR, Disjoint Set Union with path compression and union by rank',
    theory: 'DSU achieves nearly O(1) α(n) inverse Ackermann time complexity for dynamic connectivity.',
    patternsCount: 3,
    problemsCount: 14,
    solvedCount: 0,
    confidence: 0,
  },
];

export const initialDSAPatterns: DSAPattern[] = [
  {
    id: 'pat-1',
    topicId: 'top-6',
    name: 'Sliding Window (Dynamic)',
    description: 'Expand right pointer until condition breaks, shrink left pointer until valid again. Track min/max length.',
    keyTriggers: ['Longest substring', 'Subarray with constraint', 'Continuous sequence with max K flips'],
    problemCount: 8,
    masteredCount: 0,
  },
  {
    id: 'pat-2',
    topicId: 'top-4',
    name: 'HashMap + Prefix Sum',
    description: 'Store prefix sums in a hash map to find if (curSum - target) was previously seen.',
    keyTriggers: ['Subarray sum equals K', 'Contiguous subarray with sum 0', 'Count subarrays with equal 0s and 1s'],
    problemCount: 6,
    masteredCount: 0,
  },
  {
    id: 'pat-3',
    topicId: 'top-8',
    name: 'Binary Search on Answer Space',
    description: 'When the target value is within a bounded monotonic range [low, high] and a validator check(mid) is O(n).',
    keyTriggers: ['Koko Eating Bananas', 'Split Array Largest Sum', 'Capacity To Ship Packages', 'Minimize maximum'],
    problemCount: 7,
    masteredCount: 0,
  },
  {
    id: 'pat-4',
    topicId: 'top-10',
    name: 'Monotonic Decreasing Stack',
    description: 'Stack stores indices of elements in descending order to find the next greater element in O(n).',
    keyTriggers: ['Daily Temperatures', 'Next Greater Element', 'Largest Rectangle in Histogram'],
    problemCount: 6,
    masteredCount: 0,
  },
  {
    id: 'pat-5',
    topicId: 'top-12',
    name: 'Heap + HashMap',
    description: 'Count frequencies in HashMap, then use Min-Heap of size K to retain Top K frequent elements in O(N log K).',
    keyTriggers: ['Top K Frequent Elements', 'Sort Characters By Frequency', 'K closest points'],
    problemCount: 5,
    masteredCount: 0,
  },
  {
    id: 'pat-6',
    topicId: 'top-14',
    name: '1D DP — Decision at Each Index',
    description: 'Subproblem depends on choosing whether to take or skip current element (e.g. dp[i] = max(dp[i-1], dp[i-2] + nums[i])).',
    keyTriggers: ['House Robber', 'Climbing Stairs', 'Delete and Earn', 'Frog Jump'],
    problemCount: 8,
    masteredCount: 0,
  },
];

export const initialProblems: Problem[] = [
  {
    id: 'prob-1',
    topicId: 'top-6',
    topicName: 'Sliding Window',
    name: 'Longest Substring Without Repeating Characters',
    platform: 'LeetCode',
    url: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
    difficulty: 'MEDIUM',
    patterns: ['Sliding Window (Dynamic)', 'HashMap'],
    companyTags: ['Amazon', 'Google', 'Meta', 'Microsoft', 'Uber'],
    frequency: 9,
    status: 'NOT_STARTED',
    confidence: 0,
    attemptsCount: 0,
  },
  {
    id: 'prob-2',
    topicId: 'top-8',
    topicName: 'Binary Search',
    name: 'Search in Rotated Sorted Array',
    platform: 'LeetCode',
    url: 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
    difficulty: 'MEDIUM',
    patterns: ['Binary Search on Rotated Array'],
    companyTags: ['Amazon', 'Microsoft', 'Google', 'Apple', 'LinkedIn'],
    frequency: 10,
    status: 'NOT_STARTED',
    confidence: 0,
    attemptsCount: 0,
  },
  {
    id: 'prob-3',
    topicId: 'top-7',
    topicName: 'Prefix Sum',
    name: 'Subarray Sum Equals K',
    platform: 'LeetCode',
    url: 'https://leetcode.com/problems/subarray-sum-equals-k/',
    difficulty: 'MEDIUM',
    patterns: ['HashMap + Prefix Sum'],
    companyTags: ['Meta', 'Amazon', 'Google', 'Bloomberg'],
    frequency: 8,
    status: 'NOT_STARTED',
    confidence: 0,
    attemptsCount: 0,
  },
  {
    id: 'prob-4',
    topicId: 'top-14',
    topicName: 'Dynamic Programming',
    name: 'Coin Change',
    platform: 'LeetCode',
    url: 'https://leetcode.com/problems/coin-change/',
    difficulty: 'MEDIUM',
    patterns: ['1D DP — Decision at Each Index', 'Unbounded Knapsack'],
    companyTags: ['Amazon', 'Microsoft', 'Bloomberg', 'Goldman Sachs'],
    frequency: 9,
    status: 'NOT_STARTED',
    confidence: 0,
    attemptsCount: 0,
  },
  {
    id: 'prob-5',
    topicId: 'top-4',
    topicName: 'Hashing',
    name: 'Two Sum',
    platform: 'LeetCode',
    url: 'https://leetcode.com/problems/two-sum/',
    difficulty: 'EASY',
    patterns: ['HashMap'],
    companyTags: ['Amazon', 'Google', 'Apple', 'Meta', 'Adobe'],
    frequency: 10,
    status: 'NOT_STARTED',
    confidence: 0,
    attemptsCount: 0,
  },
  {
    id: 'prob-6',
    topicId: 'top-12',
    topicName: 'Heap / Priority Queue',
    name: 'Top K Frequent Elements',
    platform: 'LeetCode',
    url: 'https://leetcode.com/problems/top-k-frequent-elements/',
    difficulty: 'MEDIUM',
    patterns: ['Heap + HashMap', 'Bucket Sort'],
    companyTags: ['Amazon', 'Meta', 'Uber', 'Yelp'],
    frequency: 8,
    status: 'NOT_STARTED',
    confidence: 0,
    attemptsCount: 0,
  },
  {
    id: 'prob-7',
    topicId: 'top-9',
    topicName: 'Linked Lists',
    name: 'LRU Cache',
    platform: 'LeetCode',
    url: 'https://leetcode.com/problems/lru-cache/',
    difficulty: 'MEDIUM',
    patterns: ['Doubly Linked List + HashMap'],
    companyTags: ['Amazon', 'Microsoft', 'Google', 'Meta', 'Apple', 'Bloomberg'],
    frequency: 10,
    status: 'NOT_STARTED',
    confidence: 0,
    attemptsCount: 0,
  },
  {
    id: 'prob-8',
    topicId: 'top-13',
    topicName: 'Graphs',
    name: 'Course Schedule',
    platform: 'LeetCode',
    url: 'https://leetcode.com/problems/course-schedule/',
    difficulty: 'MEDIUM',
    patterns: ['Topological Sort (Kahn Algorithm)', 'DFS Cycle Detection'],
    companyTags: ['Amazon', 'Google', 'Twitter', 'Robinhood'],
    frequency: 9,
    status: 'NOT_STARTED',
    confidence: 0,
    attemptsCount: 0,
  },
];

export const initialTasks: Task[] = [
  {
    id: 'task-1',
    userId: 'usr_default_101',
    title: 'Day 1: Setup Local Development Environment & GitHub Repositories',
    description: 'Install Node.js, Git, VSCode extensions, and configure GitHub SSH keys',
    category: 'PROJECT',
    priority: 'HIGH',
    status: 'TODO',
    dueDate: '2026-09-30',
    dueTime: '11:00',
    estimatedTime: 45,
    tags: ['Day1', 'Setup', 'Git'],
    createdAt: '2026-09-30T08:00:00Z',
    updatedAt: '2026-09-30T08:00:00Z',
  },
  {
    id: 'task-2',
    userId: 'usr_default_101',
    title: 'Day 1: Review Big-O Notation & Time/Space Complexity Basics',
    description: 'Study asymptotic analysis: O(1), O(log n), O(n), O(n log n), O(n²)',
    category: 'DSA',
    priority: 'HIGH',
    status: 'TODO',
    dueDate: '2026-09-30',
    dueTime: '14:00',
    estimatedTime: 60,
    tags: ['Day1', 'DSA', 'BigO'],
    createdAt: '2026-09-30T08:00:00Z',
    updatedAt: '2026-09-30T08:00:00Z',
  },
  {
    id: 'task-3',
    userId: 'usr_default_101',
    title: 'Day 1: Modern CSS Box Model & HTML5 Semantics',
    description: 'Deep dive into content-box vs border-box, semantic tags, and layout flexbox',
    category: 'WEB_DEV',
    priority: 'MEDIUM',
    status: 'TODO',
    dueDate: '2026-09-30',
    dueTime: '17:00',
    estimatedTime: 45,
    tags: ['Day1', 'WebDev', 'CSS'],
    createdAt: '2026-09-30T08:00:00Z',
    updatedAt: '2026-09-30T08:00:00Z',
  },
  {
    id: 'task-4',
    userId: 'usr_default_101',
    title: 'Day 1: OS Fundamentals — Process vs Thread & Memory Hierarchy',
    description: 'Understand CPU registers, L1/L2/L3 cache, RAM, and process address space',
    category: 'CS',
    priority: 'MEDIUM',
    status: 'TODO',
    dueDate: '2026-09-30',
    dueTime: '19:30',
    estimatedTime: 45,
    tags: ['Day1', 'CS', 'OS'],
    createdAt: '2026-09-30T08:00:00Z',
    updatedAt: '2026-09-30T08:00:00Z',
  },
];

export const initialProjects: ProjectItem[] = [
  {
    id: 'proj-1',
    name: 'Employee Offboarding Automation',
    description:
      'Enterprise workflow system to automate credential revoking, asset returns, and department sign-offs across IT, HR, and Security.',
    techStack: ['React', 'Node.js', 'Express', 'MongoDB', 'JWT', 'Tailwind CSS', 'Docker'],
    githubUrl: 'https://github.com/nikhitha-dev/employee-offboarding-automation',
    liveUrl: 'https://offboarding-demo.vercel.app',
    startDate: '2026-09-30',
    deadline: '2026-11-15',
    progress: 0,
    resumeBullet:
      'Architected an automated employee offboarding platform reducing IT deprovisioning time by 75%; implemented role-based JWT auth, real-time audit logging, and automated Slack/email webhook pipelines.',
    documentation:
      'Backend uses MVC pattern with Express routers, Mongoose schemas, and BullMQ for asynchronous webhook delivery. Frontend built with React 18, React Hook Form, and TanStack Table.',
    tasks: [
      { id: 'pt-1', title: 'Backend project setup and folder structure', isCompleted: false, isBug: false, isFeature: true },
      { id: 'pt-2', title: 'MongoDB connection & User schema with roles', isCompleted: false, isBug: false, isFeature: true },
      { id: 'pt-3', title: 'JWT Authentication & Refresh token endpoint', isCompleted: false, isBug: false, isFeature: true },
      { id: 'pt-4', title: 'Offboarding Request CRUD APIs with status state machine', isCompleted: false, isBug: false, isFeature: true },
      { id: 'pt-5', title: 'Frontend Dashboard layout & Offboarding request table', isCompleted: false, isBug: false, isFeature: true },
      { id: 'pt-6', title: 'Fix token expiry race condition during simultaneous API calls', isCompleted: false, isBug: true, isFeature: false },
      { id: 'pt-7', title: 'Automated email notification upon status transition', isCompleted: false, isBug: false, isFeature: true },
      { id: 'pt-8', title: 'Docker containerization & CI/CD workflow', isCompleted: false, isBug: false, isFeature: true },
    ],
  },
  {
    id: 'proj-2',
    name: 'DevTrack AI — Personal Developer Operating System',
    description:
      'Full-stack platform consolidating DSA roadmap, ATS job tracker, Pomodoro study sessions, spaced repetition engine, and DevMentor AI.',
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Prisma', 'PostgreSQL', 'Recharts'],
    githubUrl: 'https://github.com/nikhitha-dev/devtrack-ai',
    startDate: '2026-09-30',
    deadline: '2026-11-30',
    progress: 0,
    resumeBullet:
      'Engineered DevTrack AI, a personal developer productivity OS with adaptive spaced repetition (SM-2), full ATS job pipeline, Pomodoro analytics, and context-aware AI mentorship.',
    tasks: [
      { id: 'pt-201', title: 'Normalized 25+ model Prisma PostgreSQL schema', isCompleted: false, isBug: false, isFeature: true },
      { id: 'pt-202', title: 'Task Manager with Natural Language Quick Add', isCompleted: false, isBug: false, isFeature: true },
      { id: 'pt-203', title: 'Adaptive Spaced Repetition engine based on confidence', isCompleted: false, isBug: false, isFeature: true },
      { id: 'pt-204', title: 'ATS Kanban board with follow-up reminders', isCompleted: false, isBug: false, isFeature: true },
    ],
  },
];

export const initialWebDevTopics: WebDevTopic[] = [
  {
    id: 'web-1',
    name: 'HTML & Modern CSS',
    category: 'Frontend',
    concepts: ['Semantic Elements', 'Flexbox', 'CSS Grid', 'Tailwind CSS', 'Responsive Design', 'A11y ARIA'],
    lessonsCount: 8,
    completedLessons: 0,
    confidence: 1,
  },
  {
    id: 'web-2',
    name: 'JavaScript Deep Dive',
    category: 'Frontend & Backend',
    concepts: ['Scope & Closures', 'Event Loop & Microtasks', 'Promises & Async/Await', 'Prototypes', 'ES6+ Modules', 'DOM Manipulation'],
    lessonsCount: 12,
    completedLessons: 0,
    confidence: 1,
  },
  {
    id: 'web-3',
    name: 'React 18 & Ecosystem',
    category: 'Frontend',
    concepts: ['Virtual DOM & Reconciliation', 'State & Props', 'Hooks (useState, useEffect, useMemo, useCallback)', 'Custom Hooks', 'Context API', 'Performance Optimization'],
    lessonsCount: 14,
    completedLessons: 0,
    confidence: 1,
  },
  {
    id: 'web-4',
    name: 'Node.js & Express.js',
    category: 'Backend',
    concepts: ['V8 Engine & Libuv', 'Event Driven Architecture', 'Streams & Buffers', 'REST API Design', 'Middleware Architecture', 'Error Handling'],
    lessonsCount: 10,
    completedLessons: 0,
    confidence: 1,
  },
  {
    id: 'web-5',
    name: 'MongoDB & Mongoose',
    category: 'Database',
    concepts: ['Document Modeling', 'CRUD Operations', 'Aggregation Pipeline', 'Indexes & Query Optimization', 'Schema Validation'],
    lessonsCount: 8,
    completedLessons: 0,
    confidence: 1,
  },
  {
    id: 'web-6',
    name: 'Authentication & Security',
    category: 'Backend & Security',
    concepts: ['JWT & Refresh Tokens', 'OAuth 2.0 / Google Auth', 'HttpOnly Cookies', 'Password Hashing (bcrypt)', 'CORS, CSRF & XSS Prevention'],
    lessonsCount: 8,
    completedLessons: 0,
    confidence: 1,
  },
  {
    id: 'web-7',
    name: 'Next.js 14 & TypeScript',
    category: 'Full Stack',
    concepts: ['App Router & Layouts', 'Server vs Client Components', 'Server Actions', 'API Routes', 'Static & Dynamic Rendering', 'TypeScript Strict Mode'],
    lessonsCount: 10,
    completedLessons: 0,
    confidence: 1,
  },
  {
    id: 'web-8',
    name: 'Testing & CI/CD Deployment',
    category: 'DevOps & Quality',
    concepts: ['Unit Testing with Jest', 'React Testing Library', 'Integration Tests', 'Docker containerization', 'GitHub Actions CI/CD', 'Vercel / Render deployment'],
    lessonsCount: 7,
    completedLessons: 0,
    confidence: 1,
  },
];

export const initialHabits: HabitItem[] = [
  {
    id: 'hab-1',
    name: 'Wake up before 7:00 AM',
    description: 'Enables morning focus block before distractions begin',
    currentStreak: 0,
    longestStreak: 0,
    targetDays: [0, 1, 2, 3, 4, 5, 6],
    logs: {},
  },
  {
    id: 'hab-2',
    name: 'Study 4+ Hours Daily',
    description: 'Minimum dedicated deep work target for SDE-1 roadmap',
    currentStreak: 0,
    longestStreak: 0,
    targetDays: [0, 1, 2, 3, 4, 5, 6],
    logs: {},
  },
  {
    id: 'hab-3',
    name: 'Solve 2 DSA Problems',
    description: 'One new problem + one spaced repetition revision',
    currentStreak: 0,
    longestStreak: 0,
    targetDays: [0, 1, 2, 3, 4, 5, 6],
    logs: {},
  },
  {
    id: 'hab-4',
    name: 'No Junk Food & 3L Water',
    description: 'Mental clarity and steady energy throughout study sessions',
    currentStreak: 0,
    longestStreak: 0,
    targetDays: [0, 1, 2, 3, 4, 5, 6],
    logs: {},
  },
  {
    id: 'hab-5',
    name: 'Read 20 mins Tech Blog / Docs',
    description: 'System design blogs, React changelog, RFCs',
    currentStreak: 0,
    longestStreak: 0,
    targetDays: [1, 2, 3, 4, 5],
    logs: {},
  },
];

export const initialMoodLogs: MoodEntry[] = [];

// Empty initial applications — user adds companies as they apply
export const initialJobApplications: JobApplicationItem[] = [];

export const initialSavedJobListings: JobListing[] = [];

export const initialStudySessions: StudySessionItem[] = [];
